# Generated by Django 5.1.1 on 2024-11-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='especialidades/')),
                ('contacto', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField(default='09:00')),
                ('horario_fin', models.TimeField(default='17:00')),
                ('max_atenciones_diarias', models.IntegerField(default=5)),
                ('valor_consulta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('codigo_descuento', models.CharField(blank=True, max_length=5, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
